[package]
name = "descholar"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "21.6.0"}
soroban-token-sdk = { version = "21.6.0" } 

[features]
testutils = ["soroban-sdk/testutils"]
